show databases;
use customer_shopping_analysis;
select * from customer_data;

select * from customer_data limit 10;


-- 1. what is the total revenue generated by the male and female customer ?
select gender
,sum(purchase_amount) as total_revenue
from customer_data
group by gender;

-- 2. which customer used a discount but still spent more than the average purchase amount ?
select customer_id, purchase_amount
	from customer_data
    where discount_applied = 'Yes' and
    purchase_amount >= (select avg(purchase_amount)from customer_data);
    
-- 3. which are the top 5 product with the highest average review rating ?
select item_purchased, round(avg(review_rating),1) as avg_review_rating
from customer_data
group by item_purchased
order by avg_review_rating desc limit 5;

-- 4. Compare the average purchase amounts between standard and Express shipping ?

select shipping_type , round(avg(purchase_amount),2) as avg_pruchase_amount_by_shipping
from customer_data
where shipping_type in ('Standard' , 'Express')
group by shipping_type;

-- 5. Do subscribed customer spends more ? compare average spend and total revenue between subscribers and non subscribers ?

select count(customer_id) as total_customer, 
sum(purchase_amount) as total_revenue , 
subscription_status ,
round(avg(purchase_amount),2) as average_amount
from customer_data
group by subscription_status;


-- 6. which 5 product has the highest percentage of purchases with discount applied ?
select item_purchased,
round(sum(case when discount_applied = 'Yes'  then 1 end) /count(*) * 100,2) as discount_rate
from customer_data
group by item_purchased
order by discount_rate desc 
limit 5 ;

-- 7. Segment customer into new , returning and loyal based on their total 
-- number of previous purchase and show the count of each segment
with customer_type as (
select customer_id , previous_purchases,
case when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning' 
else 'Loyal' end as customer_segment
from customer_data)
select customer_segment , count(*) as 'Number of customer'
from customer_type 
group by customer_segment;


-- 8. what is the top 3 most purchased product with in each category
with item_count as
(select category , item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer_data
group by category , item_purchased)
select item_rank , category , item_purchased , total_orders
from item_count
where item_rank <= 3;



-- 9. Are customers who are repeat buyers (mre than previous 5 purchases) also likelt to subscribe ?
select subscription_status , 
count(customer_id) as repeat_buyers
from customer_data
where previous_purchases > 5
group by subscription_status;


-- 10. what is the revenue contribution of each age group ?

select age_group , sum(purchase_amount) as revenue_contribution
from customer_data
group by age_group
order by revenue_contribution desc ;

